Fix Date Inputs wrong border color on focus element
rentalutions/elements pull request #127
Opened 2020-10-22 17:09 UTC by antonzaloznyy

https://airtable.com/tblkoPjYfI9Xkcynn/viw6843tbMpwyfaM5/receb0HhhJMohXPWS?blocks=hide

2020-10-22 21:11 UTC, pkrawc requested changes
Thanks for opening this fix @antonzaloznyy. I've made one comment I'd like to see changed. I'm also seeing a weird shifting of the line-height of the label text when you focus into the input, but we can probably solve that outside this PR.

2020-10-22 21:11 UTC, pkrawc commented on packages/input/src/index.js
> +  &.date:not(.error) input:focus,
I was seeing weird behavior when testing this locally. It would override the input but only until I filled in most of the date? I'm not sure why exactly, possibly because onChange doesn't fire for date inputs until it's a valid date. Anyway I recommend changing the selector to `&.date.raised:not(.error) input`

2020-10-23 11:26 UTC, antonzaloznyy commented
Unfortunately `&.date.raised:not(.error) input` doesn't fix a problem for me (

2020-10-23 16:23 UTC, pkrawc submitted a review, later dismissed
I've updated the input styling so that it should work now. We just needed to remove the selector below so that it wasn't overriding the `:not`.

I'm approving this PR as it stands, pull down my commit and let me know what you think before I merge this into the release branch.

2020-10-23 18:47 UTC, antonzaloznyy commented
I've tested and it works great. Thank you!

2020-10-23 20:15 UTC, pkrawc approved these changes

2020-10-23 20:18 UTC, merged