Update/input error text position
rentalutions/elements pull request #133
Opened 2020-11-16 19:19 UTC by creaumond

**Why**
Input currently implements error text using `position: absolute`. When the error text is too long, it will render on top of whatever is below it.

**Solution**
Move error text out of the `label` box and remove `absolute` style.

2020-11-16 19:50 UTC, pkrawc requested changes

2020-11-16 19:50 UTC, pkrawc commented on packages/input/src/index.js
> +        as="label"
This box is supposed to be the input, not the label, you have duplicate `as` props declared here.

2020-11-16 19:50 UTC, pkrawc commented on packages/input/src/index.js
> +    <>
Prefer `Fragment` and pass in a key if possible.

I'm also not sure I prefer this architecture to just changing the border to be in the input element inside the label and keeping the error inside the label as well. There's likely something we can do to switch the `labelled-by` prop when an error exists to help disabled users recognize that there's an error on the component.

2020-11-16 19:51 UTC, pkrawc commented
Some counter-arguments to changing error text to be relatively positioned.

1. Layout shift is always annoying, especially when concerning text inputs and mobile. Any movement of focus for a user is a huge distraction in filling out a form.

2. Input error character length should be kept as terse as possible. People don't want to read a paragraph of text if they can help it, they just want to know how to fix the problem.

2020-11-16 19:53 UTC, creaumond commented on packages/input/src/index.js
> +        as="label"
I did not update that box - I think it is just a weird thing with how the changes are rendering out in github. `as={as}` is the next `Box` down.

2020-11-18 16:52 UTC, wade00 commented
Some counter-counter-arguments:

We're implementing this in an application that has complex interactions and the errors we surface can be hard to succinctly describe. How do you want to shorten `The lease dates overlap with another active lease in your account`? `Start date taken`?

I am all for economy when it comes to error messages, but I want to decouple our error messages (as much as we can) from our UI. That might sound really naive because the dev should be aware of the UI context the error is rendering in, but right now we have overhead for developers that need to either a. choose a shortened error message over a more descriptive one, or b. adjust the UI to accommodate the longer error message by adding margin around the input, which will lead to non-standard spacing.

So yes, layout shift is annoying, but is it something we can live with?

And yes, users don't want to read a paragraph, but if they want to know how to fix the problem don't we need to opt for descriptive instead of concise?

2020-11-18 16:56 UTC, Jabbs commented
A thought:

Could we cut off long messages with a "show more" or "show full error" link that extends the page (relative position) or perhaps opens a modal with the full message? Then the screen isn't jumping around on the user

(I agree with the layout shift being annoying, but I'm not sure all users would mind)

2020-11-18 16:59 UTC, quaardvark commented
I think it might be decent to have it as an opt-in prop with breakpoints support: it highly depends on the from composition and/or device, - layout shift is way less annoying in stacked forms, while very jarring in grid-like forms. Animating this shifting opt-in error would also be helpful

2020-11-18 17:07 UTC, quaardvark commented
> `The lease dates overlap with another active lease in your account`

I think complex messages like these are better displayed as `FORM_ERROR` than under the inputs, while the relevant inputs can be just marked erroneous without the message, so it's a bit of a downstream issue

2020-11-18 17:09 UTC, wade00 commented
> > `The lease dates overlap with another active lease in your account`
> 
> @wade00 I think complex messages like these are better displayed as `FORM_ERROR` than under the inputs, while the relevant inputs can be just marked erroneous without the message, so it's a bit of a downstream issue

@quaardvark I generally agree with this. And our answer potentially changes if we come up with a comprehensive guide for what's a form error vs. inline. If we stick to format and presence type validations we're better able to commit to concise errors.

2020-11-18 17:48 UTC, creaumond commented
The one thing I would push back against is that this is an issue of error character length. While this could use some improvement, this is not a particularly long error
![Screen Shot 2020-11-18 at 11 44 30 AM](https://user-images.githubusercontent.com/7423000/99567395-b8a9d000-2993-11eb-9015-b27decd90cda.png)

2020-11-18 17:49 UTC, pkrawc commented
> The one thing I would push back against is that this is an issue of error character length. While this could use some improvement, this is not a particularly long error
> ![Screen Shot 2020-11-18 at 11 44 30 AM](https://user-images.githubusercontent.com/7423000/99567395-b8a9d000-2993-11eb-9015-b27decd90cda.png)

This could be shortened to "Incorrect Password"

2020-11-18 17:50 UTC, pkrawc commented
UX wise we should probably never imply that the user made the error (even if they did).

2020-11-18 17:51 UTC, pkrawc commented
> "The lease dates overlap with another active lease in your account"

Could be shortened to "Overlapping lease dates" @wade00

2020-11-18 18:08 UTC, wade00 commented
> > "The lease dates overlap with another active lease in your account"
> 
> Could be shortened to "Overlapping lease dates" @wade00

Let's not compete to make the shortest error message. Let's focus this on how we create a system that doesn't require devs to count characters in an error message.

I generally like the idea of outlining constraints for "what is a form error" vs a field error. We have already talked about better form level error handling as a team I believe, and Anton is doing some relevant work on the tenant stepper right now.

Making this standard practice will require a shift away from the Rails convention of putting the error on the field that error-ed. We do this already in spots, when we put an error under a `base` key if it doesn't apply to a specific field so we can continue with that path, but we should do so with careful consideration.

Using field level validations for "birth date required" or "invalid phone number", but form errors for "Your lease is overlapping with another active lease for this unit" is easy for me to reason about from a UX standpoint. I think it would come with some implementation headaches, though, and I don't know when is a good time to take something on like this.

2020-11-18 18:35 UTC, pkrawc commented
I don't think it's entirely the engineers job to think of concise error messages on fields but it shouldn't be overlooked @wade00. All the situations in this thread (and all that I've encountered throughout the app) could be solved by being more terse in error messaging.

Terse error messages don't even mean that we can't update input fields to have relatively positioned errors but if we want to change the way we do that here then I'll likely want a PR opened that updates all inputs in the app to remove any extra padding we've assigned to work with our current implementation before I'll allow this PR to be pushed to the release branch.

2020-11-18 18:43 UTC, creaumond commented
> I don't think it's entirely the engineers job to think of concise error messages on fields but it shouldn't be overlooked @wade00. All the situations in this thread (and all that I've encountered throughout the app) could be solved by being more terse in error messaging.
> 
> Terse error messages don't even mean that we can't update input fields to have relatively positioned errors but if we want to change the way we do that here then I'll likely want a PR opened that updates all inputs in the app to remove any extra padding we've assigned to work with our current implementation before I'll allow this PR to be pushed to the release branch.

All valid points. We chatted a bit about this on Slack, but could we release a beta version with this to understand what the actual impact would be?

2020-11-18 19:07 UTC, pkrawc commented
`@rent_avail/input@0.4.0-beta.0` is published on npm, it's a tagged as a beta release so there shouldn't be any trouble with people randomly upgrading to it.

2020-11-18 22:01 UTC, creaumond commented
I have made one additional update that I think helps to improve this which sets a min-height on an input. 

After pulling in the original changes, it was apparent there are two separate things we need to solve for. Client validations - which are small and almost always will render onto one line, but the user will see often as they are clicking through the app. These are mostly not problematic right now with the `absolute` approach as they almost always fit on one line.

Server validations though are often longer, and those are the ones we are facing troubles with.

To help solve for both issues, I've set a min-height on the input element, which allows one line of text to render without moving around any other elements on the screen. If an input error does render on multiple lines from a server validation, it will handle that by pushing other elements down. Because this is typically going to come from the user clicking a submit button to make the request, I think this is probably a good middle ground. 

![Screen Shot 2020-11-18 at 3 45 50 PM](https://user-images.githubusercontent.com/7423000/99593494-5a8ee400-29b7-11eb-961b-1b4af47a574b.png)

2020-11-25 15:36 UTC, pkrawc requested changes
Need to update a minor version to merge into release.

2020-11-25 16:01 UTC, pkrawc commented on packages/input/src/index.js
> -          clipPath: isTextarea ? "inset(3rem 0 0 0)" : "none",
We can't remove this clip-path. It's needed if the element is a textarea.

2020-11-25 16:02 UTC, pkrawc commented on packages/input/src/index.js
> +          "&:focus-within": {
This isn't `focus-within` if it's the actual element that's being focused. And this will reintroduce the "blue border if error but currently in focus" bug.

2020-11-25 17:51 UTC, pkrawc approved these changes
Graduated pre-release package and verified on dependents.

2020-11-25 19:14 UTC, merged