refactor: add ARIA attributes and keyboard nav to Menu component
rentalutions/elements pull request #198
Opened 2022-08-04 02:20 UTC by mzbeetnoff

Add ARIA attributes consistent to the ARIA Disclosure Navigation
Menu design pattern.

Add keyboard navigation shortcuts consistent with disclosure design
pattern.

Lock body scroll when menu is open, unlock body scroll when menu is
closed.

Refs: AT-3492

2022-08-05 10:22 UTC, quaardvark commented on packages/menu/src/index.js
> +  }, [isOpen])
Not sure if the menu warrants the body scroll lock, but if it is up to the spec and in agreement with design team, we probably need to clean that up on unmount as well.

2022-08-05 13:35 UTC, pkrawc requested changes
Overall looks great, few minor suggestions and then added to Dima's comment on the bodyScrollLock hook usage.

2022-08-05 13:35 UTC, pkrawc commented on packages/menu/src/index.js
> +import { Box, Card } from "@rent_avail/layout"
Can we update these to be imported from `@rent_avail/core`? Confusing for sure but layout is an unneeded package now that all those elements have been consolidated to core.

2022-08-05 13:35 UTC, pkrawc commented on packages/menu/src/index.js
> +  }, [isOpen])
Agree that the body scroll lock probably isn't needed.

This does bring up the idea of focus capture though, we'll want something like a `useRovingIndex` hook to make sure that the focus stays within the menu unless the user takes a specific action. 

I think that's to WCAG spec, dunno if it's needed to implement now though.

2022-08-05 13:35 UTC, pkrawc commented on packages/menu/src/index.js
> +      <MenuWrapper>{children}</MenuWrapper>
Why can't the MenuWrapper logic be in the Menu component? Can we remove the MenuWrapper component if we move all the event handlers into this function?

2022-08-05 13:35 UTC, pkrawc commented on packages/menu/src/index.js
> +        }
You can actually do this in the sx prop. No need for using styled here.

2022-08-05 13:35 UTC, pkrawc commented on packages/menu/src/index.js
> +        outline: "none",
```suggestion
        outline: "none",
        "&:hover, &:first-child:focus": {
          background: "ui_300"
        },
        "&:not(:last-of-type)": {
          borderBottom: "1px solid transparent", // These two lines are a hack to not have to interpolate a string. I hate it.
          borderBottomColor: "ui_500"
        }
```

2022-08-05 13:35 UTC, pkrawc commented on packages/menu/src/index.js
> +        case "ArrowLeft": {
Should we check for LTR text here? That would switch the left and right arrow key functions.

2022-08-05 13:35 UTC, pkrawc commented on packages/menu/src/index.js
>          if (typeof onClick === "function") onClick(e)
Oh type safety...

Good to check though.

2022-08-05 18:39 UTC, mzbeetnoff commented on packages/menu/src/index.js
> +      <MenuWrapper>{children}</MenuWrapper>
Yep shouldn't be an issue will make the change 👍

2022-08-05 19:18 UTC, mzbeetnoff commented on packages/menu/src/index.js
> +        case "ArrowLeft": {
I'm not sure we do? My reasoning is that we only officially support US english as our supported language.

2022-08-05 19:19 UTC, mzbeetnoff commented on packages/menu/src/index.js
> +  }, [isOpen])
I've removed it in my next commit. I used the body lock scrolling to prevent scrolling the page up and down when the menu is open and a user is pressing the Up and Down arrow keys. Adding preventDefault to these events has the same effect.

2022-08-08 16:54 UTC, quaardvark commented on packages/menu/src/index.js
> +  }, [isOpen])
We still probably want to clean up those effects on unmount

2022-08-08 22:06 UTC, mzbeetnoff commented on packages/menu/src/index.js
> +  }, [isOpen])
Right, I agree we probably do to future proof this component. I added the required logic to remove event listeners in my last commit.

2022-08-11 16:51 UTC, pkrawc commented on packages/menu/src/index.js
> +        case "ArrowLeft": {
I'm fine with this logic for now. I would say that we only support US rental properties, but there's no reason to only support US english in the US. Plenty of people still use their browser with a default language other than that in the US.

2022-08-11 16:52 UTC, pkrawc requested changes
Other than removing the layout dependency, this looks good to go to me.

2022-08-11 16:52 UTC, pkrawc commented on packages/menu/package.json
>      "@rent_avail/layout": "^0.3.13",
Can probably remove the layout dependency, yeah?

2022-08-15 15:02 UTC, quaardvark submitted a review, later dismissed

2022-08-15 16:14 UTC, pkrawc approved these changes

2022-08-15 16:17 UTC, merged