At 4880 popover has incorrect orientation
rentalutions/elements pull request #201
Opened 2022-09-10 02:01 UTC by mzbeetnoff

2022-09-12 14:37 UTC, quaardvark reviewed
Code looks good, but don't have bandwith to test thorougly right now

2022-09-21 16:21 UTC, pkrawc commented
Will pull this down and review today!

2022-09-21 19:39 UTC, pkrawc commented on packages/popover/src/index.js
> +  const paddingY = 12
Should these be user editable? A prop on the component perhaps with default values?

2022-09-21 22:16 UTC, mzbeetnoff commented on packages/popover/src/index.js
> +  const paddingY = 12
I'm not sure it's necessary? 🤔
A consumer of this component can style the padding and margins of the target element which should have the same effect. Or am I'm missing the idea completely, what are you thinking?

2022-09-22 13:56 UTC, pkrawc commented on packages/popover/src/index.js
> +  const paddingY = 12
My question then would be why even calculate for it here? It's nice to have defaults but if it can be left up to the consumer then why make it part of the position calc?

2022-09-22 19:13 UTC, pkrawc requested changes
I'm not sure if this existed before or not but if there is no position relative on the body--assuming that's the container--then the position on the popover is calculated incorrectly.

`closestScrollable` should return the body if nothing lower is scrollable, but something weird (read I don't understand what) is happening with the box-model when no relative positioning is defined.

2022-09-22 19:49 UTC, mzbeetnoff commented on packages/popover/src/index.js
> +  const paddingY = 12
I think I see what you're saying and it makes sense. I will make these user editable with default values in the next commit.

2022-09-26 21:34 UTC, mzbeetnoff commented on packages/popover/src/index.js
> +  const paddingY = 12
Added the configurable property `paddingY` to the `Popover` component. I didn't add a `paddingX` property as I can't see how this would be used currently. The popover always opens either above or below the target, but is always aligned to the left or right side of the menu target.

2022-09-26 21:45 UTC, mzbeetnoff commented
> I'm not sure if this existed before or not but if there is no position relative on the body--assuming that's the container--then the position on the popover is calculated incorrectly.
> 
> `closestScrollable` should return the body if nothing lower is scrollable, but something weird (read I don't understand what) is happening with the box-model when no relative positioning is defined.

@pkrawc I believe I have corrected the issue. As far as I can tell the issue has existed for sometime, I was able to verify this by checking out an older `Popover` version  [here](https://github.com/rentalutions/elements/blob/697d0bec3744266baaf8cd0d430690e0dd45be7d/packages/popover/src/index.js) and using the example story you included to demonstrate it. It seems the issue is related to setting the margin value to something other than 0, and how the resize handler calculates the targetBounds.

![image](https://user-images.githubusercontent.com/106633502/192386408-3d2510d5-d386-49d7-80a8-193efb013d4e.png)

2022-09-26 21:45 UTC, mzbeetnoff commented
> I'm not sure if this existed before or not but if there is no position relative on the body--assuming that's the container--then the position on the popover is calculated incorrectly.
> 
> `closestScrollable` should return the body if nothing lower is scrollable, but something weird (read I don't understand what) is happening with the box-model when no relative positioning is defined.

@pkrawc I believe I have corrected the issue. As far as I can tell the issue has existed for sometime, I was able to verify this by checking out an older `Popover` version  [here](https://github.com/rentalutions/elements/blob/697d0bec3744266baaf8cd0d430690e0dd45be7d/packages/popover/src/index.js) and using the example story you included to demonstrate it. It seems the issue is related to setting the margin value to something other than 0, and how the resize handler calculates the targetBounds.

![image](https://user-images.githubusercontent.com/106633502/192386408-3d2510d5-d386-49d7-80a8-193efb013d4e.png)

2022-09-26 21:47 UTC, mzbeetnoff commented on packages/popover/src/index.js
> +  const targetBounds = useResize(targetRef, targetRef.parent)
This is how I was able to fix the issue mentioned in the comments. Instead of passing the `container` to the resize handler, I instead now pass the targetRef parent.

2022-09-27 00:22 UTC, mzbeetnoff commented
> > I'm not sure if this existed before or not but if there is no position relative on the body--assuming that's the container--then the position on the popover is calculated incorrectly.
> > `closestScrollable` should return the body if nothing lower is scrollable, but something weird (read I don't understand what) is happening with the box-model when no relative positioning is defined.
> 
> @pkrawc I believe I have corrected the issue. As far as I can tell the issue has existed for sometime, I was able to verify this by checking out an older `Popover` version [here](https://github.com/rentalutions/elements/blob/697d0bec3744266baaf8cd0d430690e0dd45be7d/packages/popover/src/index.js) and using the example story you included to demonstrate it. It seems the issue is related to setting the margin value to something other than 0, and how the resize handler calculates the targetBounds.
> 
> ![image](https://user-images.githubusercontent.com/106633502/192386408-3d2510d5-d386-49d7-80a8-193efb013d4e.png)

@pkrawc I reverted the change that fixed your popover example story because it was breaking the menu portal usage story and also because I feel the fix should be made in useResize. I'm kind of thinking we should revisit this issue separately in a later pull request / jira because it seems out of scope with this change. what do you think?

2022-09-27 14:41 UTC, pkrawc approved these changes
Cool. As long as we're thinking it won't effect any consumers (by introducing something new that they don't expect) I agree that it's likely outside the scope of this fix. Thank you for following up on all this.

2022-09-27 14:42 UTC, pkrawc approved these changes

2022-09-27 17:27 UTC, merged