[RENA-6556] Update "Switch" off state background color
rentalutions/elements pull request #259
Opened 2024-04-08 20:24 UTC by jgrubard

### Resolves

|Type|URL|
| - | - |
|JIRA Ticket|https://moveinc.atlassian.net/browse/RENA-6556|

### Why

Last year there was an [update](https://github.com/rentalutions/elements/pull/213/files#diff-f57fead3f2ce21739fc0bf5adad5b9bdb86f59cf48f99820f28118bcea363c18) to the Switch component in the elements repo that changed the background color when the switch is "off". This clashes with some of the background colors in Avail, using the exact same color and does not appear to be an intentional change.

This can be easily overridden with custom styling, but fixing it at the source means we won’t require any custom styling to use the component properly.

It can be seen in the Elements Repo storybook that when the switch is off, the background blends with the background in storybook:
* https://design.avail.co/?path=/story/packages-controls--switch-story

The color used to be ui_500 color, but now it’s ui_300, and should be reverted to the original color to prevent issues in the UI.

### Solution

Update the `baseTheme` `background.secondary` color. Currently it's only being used in the switch component, so I don't see this change as having too much of an impact elsewhere.

### Screenshots

TBD

2024-04-09 16:10 UTC, pkrawc commented
Hmm. I don't actually think this is the right solution. The checkbox shouldn't be using the BG token set. If we change this I would expect the app background and everything to be changed.

I think instead we should add a secondary token to the `interactive` object and make it ui_300.

Does that make sense?

2024-04-09 16:11 UTC, pkrawc requested changes
We shouldn't change this token.

We should add an `interactive.secondary` token === ui_500.

2024-04-09 19:33 UTC, jgrubard commented
>Hmm. I don't actually think this is the right solution. The checkbox shouldn't be using the BG token set. If we change this I would expect the app background and everything to be changed.
>
>I think instead we should add a secondary token to the interactive object and make it ui_500.
>
>Does that make sense?

@pkrawc Yeah, this makes sense. For what it's worth, I don't think the app background would change since it looks like this is explicitly set in `.storybook/manager.tsx`, but I also agree that we should add a new interactive token instead of updating the existing background token.

2024-04-09 19:44 UTC, jgrubard commented on packages/core/src/base-theme.ts
> +    secondary: baseColors.ui_500,
@pkrawc I didn't realize that `disabled` also references `ui_500` -- do we potentially want to use `interactive.disabled` for the switch "off" state, or do you think it's fine to have two different properties referencing the same color?

2024-04-10 13:29 UTC, jgrubard commented on packages/core/src/base-theme.ts
> +    secondary: baseColors.ui_500,
@pkrawc Do you think it's necessary/useful to also add an `interactive.primary` color? Probably outside the needs of this PR, I just want to get this component fixed so I can unblock another PR in the monolith where the switch component is present but invisible in the UI, after having updated to the most recent controls package.
* https://github.com/rentalutions/rentalutions/pull/9624

2024-04-10 14:50 UTC, pkrawc approved these changes
LGTM

2024-04-10 14:51 UTC, pkrawc commented on packages/core/src/base-theme.ts
> +    secondary: baseColors.ui_500,
Eh. That's kind of how interactive.default is functioning now. I don't disagree that primary is probably better than default as a token name, but lets leave it for now.

2024-04-10 14:51 UTC, merged