resolves #RENA-6059
rentalutions/elements pull request #261
Opened 2024-04-10 16:06 UTC by stassribnyi

[RENA-6059](https://moveinc.atlassian.net/browse/RENA-6059)

- Adding a new TwitterX icon for further updates in UI

2024-04-10 16:24 UTC, jgrubard reviewed
@stassribnyi I left a few small comments. I also might be very nit-picky with this, but the new icon doesn't quite seem to match the style of the existing icons, it seems slightly bigger and stroke thickness doesn't totally match.
|Screenshot|
| - |
|![Screen Shot 2024-04-10 at 12 19 51 PM](https://github.com/rentalutions/elements/assets/29084739/550fddcf-868a-4098-8378-841378c30815)|

Any thoughts on this @pkrawc? Can you or anyone on your team provide an SVG icon that more closely matches our existing icons? We might be able to use something like this:
* https://github.com/feathericons/feather/pull/1208/files

2024-04-10 16:24 UTC, jgrubard commented on packages/icons/src/icons/twitter.js
> + */
@stassribnyi Good comment!

2024-04-10 16:24 UTC, jgrubard commented on packages/icons/src/icons/twitter-x.js
> +export const TwitterX = forwardRef(function Twitter(props, ref) {
@stassribnyi Nit-pick, but it looks like you're using 4 spaces for indentation throughout this component in stead of 2.

2024-04-10 16:24 UTC, jgrubard commented on packages/icons/src/icons/twitter-x.js
> +}
@stassribnyi Is there any reason some of the default prop values are different than what we're using for other icons?

2024-04-10 17:30 UTC, stassribnyi commented on packages/icons/src/icons/twitter-x.js
> +}
@jgrubard the icon used in @mihailbv PR works differently from what we have in this repo, without these changes we won't be able to change the color of the icon and it would have an incorrect position

With fill="currentColor" it looks like the others:
![image](https://github.com/rentalutions/elements/assets/17552161/0667bd8a-edb9-4bb8-966b-e7ed6115f75f)

With fill="none" color being applied to outline and almost invisible:
![image](https://github.com/rentalutions/elements/assets/17552161/70c95892-4179-49cf-ac01-0503dfb7e62c)

With viewBox="0 0 24 24":
![image](https://github.com/rentalutions/elements/assets/17552161/ba76e560-3f56-4d77-9aa9-d45262543817)

2024-04-10 17:31 UTC, stassribnyi commented on packages/icons/src/icons/twitter-x.js
> +}
Long story short, since icon wasn't created by our designers it works differently, so these adjustments necessary in order to make it look and feel as the rest

2024-04-10 17:33 UTC, stassribnyi commented on packages/icons/src/icons/twitter-x.js
> +export const TwitterX = forwardRef(function Twitter(props, ref) {
You are right, my IDE settings are messing again ☹️

2024-04-10 17:33 UTC, pedroroque requested changes
Houston, we have a problem!

The icons package has an automated script that auto-generates everything in src/icons, and the first step is to remove everything in there.

The usual way to add an icon is to add the SVG file and then run the compile script

2024-04-11 20:10 UTC, stassribnyi commented on packages/icons/scripts/build.js
> +  const component = await format({
There was a breaking change after `prettier-eslint` upgrade, which went unnoticed. Now format returns `Promise` and we have to await it before passing into `writeFileSync`

2024-04-11 20:11 UTC, stassribnyi commented on packages/icons/scripts/build.js
> -    eslintConfig: {
After `prettier-eslint` upgrade, there is no `extends` property in `eslintConfig`

2024-04-11 20:27 UTC, stassribnyi commented on packages/icons/svg/twitter-x.svg
Icon seems to be weird on github preview, but this is due compilation step, it is missing stroke, fill props here as well as some additional changes, but it should be displayed properly.

Storybook preview:
![image](https://github.com/rentalutions/elements/assets/17552161/f89cd05a-9ad4-4c76-abee-bc917f799709)

2024-04-12 13:00 UTC, jgrubard reviewed
@stassribnyi Nice work! I can confirm locally that the icon now looks as expected and matches our existing components. I left a small comment, but I also have a few questions outside of code review.
1. Since this is replacing the work from the following PR, it's worth communicating this to @mihailbv so we can close the duplicate PR.
    * https://github.com/rentalutions/elements/pull/258
2. Since it isn't clear that adding an icon only requires adding the svg file and running `yarn compile` in the icons package directory, can you please update the README/documentation to include instructions on how an icon should be added? This will help eliminate the guesswork for future devs.

2024-04-12 13:00 UTC, jgrubard commented on packages/icons/src/icons/twitter-x.js
> +      ></path>
@stassribnyi Assuming this was autogenerated, but I don't think we need the `class` here. I think we can keep this as a single line to match the existing components.
```suggestion
      <path d="M21.3 21.1 9.9 2.9 2.7 2.9 14.1 21.1zM2.7 21.1 9.9 14.5M14.1 9.5 21.3 2.9"></path>
```

2024-04-12 15:40 UTC, stassribnyi commented on packages/icons/src/icons/twitter-x.js
> +      ></path>
@jgrubard, it is indeed auto-generated. First, it introduces this class to the SVG icon when the minification step passes. Then, it uses the minified SVG in the .js file. I can remove it, but once anyone else runs `yarn compile`, it will be back again. The only way to get rid of this is to modify the build.js file, but I am not sure of the consequences.

2024-04-12 15:42 UTC, stassribnyi commented
> 1. his is replacing the work from the following PR, it's worth communicat

Update the old PR with [a comment](https://github.com/rentalutions/elements/pull/258#issuecomment-2052004265) to @mihailbv

2024-04-12 17:55 UTC, stassribnyi commented
After discussion with a team, we have decided to split this pull request into two separate ones.

2024-04-12 17:55 UTC, closed without merging